[MeasureAudio1]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=1

[MeasureAudio2]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=2

[MeasureAudio3]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=3

[MeasureAudio4]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=4

[MeasureAudio5]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=5

[MeasureAudio6]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=6

[MeasureAudio7]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=7

[MeasureAudio8]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=8

[MeasureAudio9]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=9

[MeasureAudio10]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=10

[MeasureAudio11]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=11

[MeasureAudio12]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=12

[MeasureAudio13]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=13

[MeasureAudio14]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=14

[MeasureAudio15]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=15

[MeasureAudio16]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=16

[MeasureAudio17]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=17

[MeasureAudio18]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=18

[MeasureAudio19]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=19

[MeasureAudio20]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=20

[MeasureAudio21]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=21

[MeasureAudio22]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=22

[MeasureAudio23]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=23

[MeasureAudio24]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=24

[MeasureAudio25]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=25

[MeasureAudio26]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=26

[MeasureAudio27]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=27

[MeasureAudio28]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=28

[MeasureAudio29]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=29

[MeasureAudio30]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=30

[MeasureAudio31]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=31

[MeasureAudio32]
Measure=Plugin
Group=Audio
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
Channel= #Channel#
AverageSize=#AverageSize#
UpdateDivider=1
BandIdx=32